import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import { useToast } from '../context/ToastContext';
import { LoadingSpinner, EmptyState, PageHeader, Card, Badge } from '../components/UI';
import {
  Sparkles, Zap, FileText, BarChart3, TrendingUp, AlertTriangle,
  Lightbulb, Trophy, Target, Clock,
} from 'lucide-react';

/* ============================================================
 * Shared helpers
 * ========================================================== */

const statusColor = (s: string | null): string => {
  switch (s) {
    case 'active': case 'accepted': case 'approved': case 'implemented': return 'green';
    case 'pending': case 'proposed': case 'open': return 'blue';
    case 'dismissed': case 'rejected': case 'closed': return 'gray';
    case 'failed': case 'overdue': return 'red';
    default: return 'gray';
  }
};

const confidenceColor = (c: number | null): string => {
  if (c == null) return 'gray';
  if (c >= 0.8) return 'green';
  if (c >= 0.5) return 'yellow';
  return 'red';
};

const fmtPct = (c: number | null): string => (c != null ? `${Math.round(c * 100)}%` : '—');
const fmtDate = (s: string | null) => (s ? new Date(s).toLocaleDateString() : '—');

/* ============================================================
 * AiRecommendationsModule
 * ========================================================== */

interface AiRecommendation {
  id: string;
  title: string | null;
  description: string | null;
  category: string | null;
  confidence: number | null;
  status: string | null;
  business_impact: string | null;
}

export function AiRecommendationsModule({ businessId }: { businessId: string }) {
  const { showToast } = useToast();
  const [items, setItems] = useState<AiRecommendation[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('ai_recommendations')
      .select('id, title, description, category, confidence, status, business_impact')
      .eq('business_id', businessId)
      .order('created_at', { ascending: false });
    if (error) {
      showToast('error', 'Failed to load recommendations');
      setItems([]);
    } else {
      setItems((data ?? []) as AiRecommendation[]);
    }
    setLoading(false);
  }, [businessId, showToast]);

  useEffect(() => { fetchData(); }, [fetchData]);

  return (
    <div>
      <PageHeader title="AI Recommendations" description="Strategic recommendations generated by the AI engine." />
      {loading ? (
        <LoadingSpinner label="Loading recommendations…" />
      ) : items.length === 0 ? (
        <EmptyState icon={Sparkles} title="No recommendations" description="AI recommendations will appear here as they are generated." />
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {items.map((r) => (
            <Card key={r.id} className="p-4 flex flex-col gap-2">
              <div className="flex items-start gap-2">
                <div className="w-8 h-8 rounded-lg bg-violet-500/15 flex items-center justify-center shrink-0">
                  <Sparkles className="w-4 h-4 text-violet-300" />
                </div>
                <p className="text-sm font-semibold text-white">{r.title || 'Untitled'}</p>
              </div>
              {r.description && <p className="text-xs text-zinc-400 line-clamp-3">{r.description}</p>}
              <div className="flex flex-wrap items-center gap-1.5">
                {r.category && <Badge color="purple">{r.category}</Badge>}
                <Badge color={confidenceColor(r.confidence)}>Confidence {fmtPct(r.confidence)}</Badge>
                <Badge color={statusColor(r.status)}>{r.status ?? '—'}</Badge>
              </div>
              {r.business_impact && (
                <div className="flex items-start gap-1.5 text-xs text-zinc-400 border-t border-white/5 pt-2 mt-auto">
                  <TrendingUp className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
                  <p className="line-clamp-2">{r.business_impact}</p>
                </div>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

/* ============================================================
 * ActionItemsModule
 * ========================================================== */

interface ActionItem {
  id: string;
  title: string | null;
  explanation: string | null;
  priority_level: string | null;
  confidence: string | null;
  status: string | null;
  recommended_action: string | null;
}

const priorityLevelColor = (p: string | null): string => {
  switch (p) {
    case 'critical': case 'urgent': return 'red';
    case 'high': return 'yellow';
    case 'medium': return 'blue';
    case 'low': return 'gray';
    default: return 'gray';
  }
};

export function ActionItemsModule({ businessId }: { businessId: string }) {
  const { showToast } = useToast();
  const [items, setItems] = useState<ActionItem[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('action_items')
      .select('id, title, explanation, priority_level, confidence, status, recommended_action')
      .eq('business_id', businessId)
      .order('created_at', { ascending: false });
    if (error) {
      showToast('error', 'Failed to load action items');
      setItems([]);
    } else {
      setItems((data ?? []) as ActionItem[]);
    }
    setLoading(false);
  }, [businessId, showToast]);

  useEffect(() => { fetchData(); }, [fetchData]);

  return (
    <div>
      <PageHeader title="Action Items" description="Prioritized actions recommended by the AI engine." />
      {loading ? (
        <LoadingSpinner label="Loading action items…" />
      ) : items.length === 0 ? (
        <EmptyState icon={Zap} title="No action items" description="Action items will appear here as the AI identifies opportunities." />
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {items.map((a) => (
            <Card key={a.id} className="p-4 flex flex-col gap-2">
              <div className="flex items-start gap-2">
                <div className="w-8 h-8 rounded-lg bg-amber-500/15 flex items-center justify-center shrink-0">
                  <Zap className="w-4 h-4 text-amber-300" />
                </div>
                <p className="text-sm font-semibold text-white">{a.title || 'Untitled'}</p>
              </div>
              {a.explanation && <p className="text-xs text-zinc-400 line-clamp-3">{a.explanation}</p>}
              <div className="flex flex-wrap items-center gap-1.5">
                <Badge color={priorityLevelColor(a.priority_level)}>{a.priority_level ?? 'medium'}</Badge>
                <Badge color="blue">Confidence {a.confidence ?? '—'}</Badge>
                <Badge color={statusColor(a.status)}>{a.status ?? '—'}</Badge>
              </div>
              {a.recommended_action && (
                <div className="flex items-start gap-1.5 text-xs text-zinc-300 border-t border-white/5 pt-2 mt-auto">
                  <Target className="w-3.5 h-3.5 text-blue-400 shrink-0 mt-0.5" />
                  <p className="line-clamp-3">{a.recommended_action}</p>
                </div>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

/* ============================================================
 * AiBriefingsModule
 * ============================================================ */

interface AiBriefing {
  id: string;
  period: string | null;
  briefing_date: string | null;
  summary: string | null;
  wins: string[] | null;
  risks: string[] | null;
  recommendations: string[] | null;
}

const StringList = ({ items, icon: Icon, color }: { items: string[] | null; icon: typeof Trophy; color: string }) => {
  if (!items || items.length === 0) return null;
  const colorMap: Record<string, string> = {
    green: 'text-emerald-400 bg-emerald-500/10',
    red: 'text-red-400 bg-red-500/10',
    blue: 'text-blue-400 bg-blue-500/10',
  };
  return (
    <div className="space-y-1">
      {items.map((item, i) => (
        <div key={i} className="flex items-start gap-2 text-xs text-zinc-300">
          <div className={`w-5 h-5 rounded shrink-0 flex items-center justify-center ${colorMap[color] || colorMap.blue}`}>
            <Icon className="w-3 h-3" />
          </div>
          <p className="line-clamp-2">{item}</p>
        </div>
      ))}
    </div>
  );
};

export function AiBriefingsModule({ businessId }: { businessId: string }) {
  const { showToast } = useToast();
  const [items, setItems] = useState<AiBriefing[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('ai_briefings')
      .select('id, period, briefing_date, summary, wins, risks, recommendations')
      .eq('business_id', businessId)
      .order('created_at', { ascending: false });
    if (error) {
      showToast('error', 'Failed to load briefings');
      setItems([]);
    } else {
      setItems((data ?? []) as AiBriefing[]);
    }
    setLoading(false);
  }, [businessId, showToast]);

  useEffect(() => { fetchData(); }, [fetchData]);

  return (
    <div>
      <PageHeader title="AI Briefings" description="Periodic AI-generated business summaries." />
      {loading ? (
        <LoadingSpinner label="Loading briefings…" />
      ) : items.length === 0 ? (
        <EmptyState icon={FileText} title="No briefings" description="AI briefings will appear here on a recurring schedule." />
      ) : (
        <div className="grid gap-4 lg:grid-cols-2">
          {items.map((b) => (
            <Card key={b.id} className="p-5 flex flex-col gap-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-9 h-9 rounded-lg bg-blue-500/15 flex items-center justify-center">
                    <FileText className="w-4.5 h-4.5 text-blue-300" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-white capitalize">{b.period ?? 'briefing'}</p>
                    <p className="text-xs text-zinc-500 flex items-center gap-1"><Clock className="w-3 h-3" /> {fmtDate(b.briefing_date)}</p>
                  </div>
                </div>
              </div>
              {b.summary && <p className="text-sm text-zinc-300 leading-relaxed">{b.summary}</p>}
              <div className="grid sm:grid-cols-3 gap-3 border-t border-white/5 pt-3">
                <div>
                  <p className="text-[10px] font-semibold text-emerald-400 uppercase tracking-wider mb-1.5 flex items-center gap-1"><Trophy className="w-3 h-3" /> Wins</p>
                  <StringList items={b.wins} icon={Trophy} color="green" />
                  {(!b.wins || b.wins.length === 0) && <p className="text-xs text-zinc-600">None</p>}
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-red-400 uppercase tracking-wider mb-1.5 flex items-center gap-1"><AlertTriangle className="w-3 h-3" /> Risks</p>
                  <StringList items={b.risks} icon={AlertTriangle} color="red" />
                  {(!b.risks || b.risks.length === 0) && <p className="text-xs text-zinc-600">None</p>}
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-blue-400 uppercase tracking-wider mb-1.5 flex items-center gap-1"><Lightbulb className="w-3 h-3" /> Recommendations</p>
                  <StringList items={b.recommendations} icon={Lightbulb} color="blue" />
                  {(!b.recommendations || b.recommendations.length === 0) && <p className="text-xs text-zinc-600">None</p>}
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

/* ============================================================
 * AiSimulationsModule
 * ========================================================== */

interface AiSimulation {
  id: string;
  simulation_type: string | null;
  scenario: string | null;
  projected_outcome: string | null;
  confidence: number | null;
  is_labelled_estimate: boolean | null;
}

export function AiSimulationsModule({ businessId }: { businessId: string }) {
  const { showToast } = useToast();
  const [items, setItems] = useState<AiSimulation[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('ai_simulations')
      .select('id, simulation_type, scenario, projected_outcome, confidence, is_labelled_estimate')
      .eq('business_id', businessId)
      .order('created_at', { ascending: false });
    if (error) {
      showToast('error', 'Failed to load simulations');
      setItems([]);
    } else {
      setItems((data ?? []) as AiSimulation[]);
    }
    setLoading(false);
  }, [businessId, showToast]);

  useEffect(() => { fetchData(); }, [fetchData]);

  return (
    <div>
      <PageHeader title="AI Simulations" description="Projected outcomes of hypothetical business scenarios." />
      {loading ? (
        <LoadingSpinner label="Loading simulations…" />
      ) : items.length === 0 ? (
        <EmptyState icon={BarChart3} title="No simulations" description="AI simulations will appear here as scenarios are modeled." />
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {items.map((s) => (
            <Card key={s.id} className="p-4 flex flex-col gap-2">
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-center gap-2 min-w-0">
                  <div className="w-8 h-8 rounded-lg bg-cyan-500/15 flex items-center justify-center shrink-0">
                    <BarChart3 className="w-4 h-4 text-cyan-300" />
                  </div>
                  <p className="text-sm font-semibold text-white truncate">{s.simulation_type || 'simulation'}</p>
                </div>
                {s.is_labelled_estimate && <Badge color="yellow">estimate</Badge>}
              </div>
              {s.scenario && <p className="text-xs text-zinc-300 line-clamp-2">{s.scenario}</p>}
              {s.projected_outcome && (
                <div className="flex items-start gap-1.5 text-xs text-zinc-400 border-t border-white/5 pt-2 mt-auto">
                  <TrendingUp className="w-3.5 h-3.5 text-blue-400 shrink-0 mt-0.5" />
                  <p className="line-clamp-3">{s.projected_outcome}</p>
                </div>
              )}
              <div className="flex items-center justify-between border-t border-white/5 pt-2 mt-auto">
                <span className="text-xs text-zinc-500">Confidence</span>
                <Badge color={confidenceColor(s.confidence)}>{fmtPct(s.confidence)}</Badge>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
