import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import { useToast } from '../context/ToastContext';
import { LoadingSpinner, EmptyState, PageHeader, Card, Badge } from '../components/UI';
import { Brain, Clock, Zap, CheckCircle2, XCircle, AlertCircle } from 'lucide-react';

interface AiTask {
  id: string;
  title: string | null;
  task_type: string | null;
  priority: string | null;
  status: string | null;
  confidence: number | null;
  expected_impact: string | null;
  created_at: string | null;
}

const priorityColor = (p: string | null): string => {
  switch (p) {
    case 'critical': case 'urgent': return 'red';
    case 'high': return 'yellow';
    case 'medium': return 'blue';
    case 'low': return 'gray';
    default: return 'gray';
  }
};

const statusColor = (s: string | null): string => {
  switch (s) {
    case 'completed': case 'done': case 'accepted': return 'green';
    case 'pending': case 'queued': case 'scheduled': return 'blue';
    case 'in_progress': case 'running': case 'processing': return 'yellow';
    case 'failed': case 'error': return 'red';
    case 'dismissed': case 'cancelled': return 'gray';
    default: return 'gray';
  }
};

const StatusIcon = ({ status }: { status: string | null }) => {
  switch (status) {
    case 'completed': case 'done': case 'accepted': return <CheckCircle2 className="w-3.5 h-3.5" />;
    case 'failed': case 'error': return <XCircle className="w-3.5 h-3.5" />;
    case 'dismissed': case 'cancelled': return <XCircle className="w-3.5 h-3.5" />;
    case 'in_progress': case 'running': case 'processing': return <AlertCircle className="w-3.5 h-3.5" />;
    default: return <Clock className="w-3.5 h-3.5" />;
  }
};

const fmtDate = (s: string | null) => (s ? new Date(s).toLocaleString() : '—');

export function AiTasksModule({ businessId }: { businessId: string }) {
  const { showToast } = useToast();
  const [items, setItems] = useState<AiTask[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('ai_tasks')
      .select('id, title, task_type, priority, status, confidence, expected_impact, created_at')
      .eq('business_id', businessId)
      .order('created_at', { ascending: false });
    if (error) {
      showToast('error', 'Failed to load AI tasks');
      setItems([]);
    } else {
      setItems((data ?? []) as AiTask[]);
    }
    setLoading(false);
  }, [businessId, showToast]);

  useEffect(() => { fetchData(); }, [fetchData]);

  return (
    <div>
      <PageHeader title="AI Tasks" description="Autonomous tasks generated by the AI engine." />
      {loading ? (
        <LoadingSpinner label="Loading AI tasks…" />
      ) : items.length === 0 ? (
        <EmptyState icon={Brain} title="No AI tasks" description="The AI engine will generate tasks as it analyzes your business." />
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {items.map((t) => (
            <Card key={t.id} className="p-4 flex flex-col gap-2">
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-center gap-2 min-w-0">
                  <div className="w-8 h-8 rounded-lg bg-violet-500/15 flex items-center justify-center shrink-0">
                    <Brain className="w-4 h-4 text-violet-300" />
                  </div>
                  <p className="text-sm font-semibold text-white truncate">{t.title || 'Untitled task'}</p>
                </div>
              </div>
              <div className="flex flex-wrap items-center gap-1.5">
                {t.task_type && <Badge color="purple">{t.task_type}</Badge>}
                <Badge color={priorityColor(t.priority)}>{t.priority ?? 'medium'}</Badge>
                <Badge color={statusColor(t.status)}>
                  <span className="inline-flex items-center gap-1"><StatusIcon status={t.status} /> {t.status ?? 'unknown'}</span>
                </Badge>
              </div>
              {t.expected_impact && (
                <div className="flex items-start gap-1.5 text-xs text-zinc-400 mt-1">
                  <Zap className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
                  <p className="line-clamp-2">{t.expected_impact}</p>
                </div>
              )}
              <div className="flex items-center justify-between border-t border-white/5 pt-2 mt-auto text-xs text-zinc-500">
                <span>Confidence: {t.confidence != null ? `${Math.round(t.confidence * 100)}%` : '—'}</span>
                <span>{fmtDate(t.created_at)}</span>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
