import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import { useToast } from '../context/ToastContext';
import { LoadingSpinner, EmptyState, PageHeader, Card, Badge } from '../components/UI';
import { Bot, Clock, TrendingUp } from 'lucide-react';

interface AiTask {
  id: string;
  business_id: string;
  title: string;
  task_type: string | null;
  priority: string | null;
  status: string | null;
  confidence: number | null;
  expected_impact: string | null;
  created_at: string;
}

export function AiTasksModule({ businessId }: { businessId: string }) {
  const { showToast } = useToast();
  const [tasks, setTasks] = useState<AiTask[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchTasks = useCallback(async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('ai_tasks')
      .select('*')
      .eq('business_id', businessId)
      .order('created_at', { ascending: false });
    if (error) {
      showToast('error', 'Failed to load AI tasks');
    } else {
      setTasks(data || []);
    }
    setLoading(false);
  }, [businessId, showToast]);

  useEffect(() => {
    fetchTasks();
  }, [fetchTasks]);

  const statusColor = (s: string | null) => {
    if (s === 'completed') return 'green';
    if (s === 'in_progress') return 'blue';
    if (s === 'pending') return 'yellow';
    if (s === 'failed') return 'red';
    if (s === 'cancelled') return 'gray';
    return 'gray';
  };

  const priorityColor = (p: string | null) => {
    if (p === 'high' || p === 'critical') return 'red';
    if (p === 'medium') return 'yellow';
    if (p === 'low') return 'gray';
    return 'gray';
  };

  if (loading) return <LoadingSpinner label="Loading AI tasks…" />;

  return (
    <div>
      <PageHeader title="AI Tasks" description="Automated tasks generated by AI" />

      {tasks.length === 0 ? (
        <EmptyState
          icon={Bot}
          title="No AI tasks"
          description="AI-generated tasks will appear here when available."
        />
      ) : (
        <div className="space-y-3">
          {tasks.map((t) => (
            <Card key={t.id} className="p-4">
              <div className="flex items-start justify-between gap-4">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 mb-2 flex-wrap">
                    <span className="text-sm font-semibold text-white">{t.title}</span>
                    {t.task_type && <Badge color="purple">{t.task_type}</Badge>}
                  </div>
                  <div className="flex items-center gap-2 flex-wrap mb-2">
                    {t.status && <Badge color={statusColor(t.status)}>{t.status}</Badge>}
                    {t.priority && <Badge color={priorityColor(t.priority)}>{t.priority}</Badge>}
                    {t.confidence != null && (
                      <span className="text-xs text-zinc-500">
                        Confidence: {Math.round(Number(t.confidence) * 100)}%
                      </span>
                    )}
                  </div>
                  {t.expected_impact && (
                    <div className="flex items-start gap-1.5 text-sm text-zinc-400">
                      <TrendingUp className="w-4 h-4 text-emerald-400 mt-0.5 shrink-0" />
                      <span>{t.expected_impact}</span>
                    </div>
                  )}
                  <p className="text-xs text-zinc-500 mt-2 flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {new Date(t.created_at).toLocaleString()}
                  </p>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
